spring:
  application:
    name: market

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:mysql://localhost:3306/daangn
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver




mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.daangn.market.dto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'NULL'



